#!/usr/bin/env python3
"""Sync GOOGLE_MAPS_API_KEY from repo-root .env into iOS + Dart local secret files.

Writes (gitignored):
  - ios/Flutter/Secrets.xcconfig
  - assets/env/app.env

Safe to run locally; does not print the key.
"""

from __future__ import annotations

from pathlib import Path


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    env_path = root / ".env"
    if not env_path.is_file():
        raise SystemExit(f"Missing {env_path}. Copy env.example to .env first.")

    key: str | None = None
    for line in env_path.read_text().splitlines():
        if line.startswith("GOOGLE_MAPS_API_KEY="):
            key = line.split("=", 1)[1].strip().strip('"').strip("'")
            break

    if not key:
        raise SystemExit("GOOGLE_MAPS_API_KEY not set in .env")

    secrets = root / "ios" / "Flutter" / "Secrets.xcconfig"
    secrets.write_text(
        "// Generated by tool/sync_maps_secrets_from_env.py — do not commit\n"
        f"GOOGLE_MAPS_API_KEY={key}\n"
    )

    asset_dir = root / "assets" / "env"
    asset_dir.mkdir(parents=True, exist_ok=True)
    (asset_dir / "app.env").write_text(f"GOOGLE_MAPS_API_KEY={key}\n")
    (asset_dir / ".gitkeep").touch()

    print(f"Synced Maps key (len={len(key)}) → {secrets.name} + assets/env/app.env")


if __name__ == "__main__":
    main()
