#!/usr/bin/env python3
"""Sync Maps keys from repo-root .env into iOS, Android, and Dart local secret files.

Writes (gitignored):
  - ios/Flutter/Secrets.xcconfig
  - android/local.properties  (merges GOOGLE_MAPS_API_KEY; keeps flutter.sdk etc.)
  - assets/env/app.env

Reads:
  - GOOGLE_MAPS_API_KEY (required) — Maps SDK / iOS-Android app-restricted OK
  - GOOGLE_MAPS_WEB_API_KEY (optional) — Places/Geocoding HTTP; must NOT be
    iOS/Android app-restricted or REST calls return REQUEST_DENIED
"""

from __future__ import annotations

from pathlib import Path


def _read_env_value(env_text: str, key: str) -> str | None:
    prefix = f"{key}="
    for line in env_text.splitlines():
        if line.startswith(prefix):
            return line.split("=", 1)[1].strip().strip('"').strip("'")
    return None


def _upsert_properties(path: Path, updates: dict[str, str]) -> None:
    """Merge key=value pairs into a Java .properties file without wiping others."""
    lines: list[str] = []
    if path.is_file():
        lines = path.read_text().splitlines()

    seen: set[str] = set()
    out: list[str] = []
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in line:
            out.append(line)
            continue
        key, _, _ = line.partition("=")
        key = key.strip()
        if key in updates:
            out.append(f"{key}={updates[key]}")
            seen.add(key)
        else:
            out.append(line)

    for key, value in updates.items():
        if key not in seen:
            out.append(f"{key}={value}")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(out) + ("\n" if out else ""))


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    env_path = root / ".env"
    if not env_path.is_file():
        raise SystemExit(f"Missing {env_path}. Copy env.example to .env first.")

    env_text = env_path.read_text()
    key = _read_env_value(env_text, "GOOGLE_MAPS_API_KEY")
    web_key = _read_env_value(env_text, "GOOGLE_MAPS_WEB_API_KEY")

    if not key:
        raise SystemExit("GOOGLE_MAPS_API_KEY not set in .env")

    secrets = root / "ios" / "Flutter" / "Secrets.xcconfig"
    secrets.write_text(
        "// Generated by tool/sync_maps_secrets_from_env.py — do not commit\n"
        f"GOOGLE_MAPS_API_KEY={key}\n"
    )

    android_props = root / "android" / "local.properties"
    _upsert_properties(android_props, {"GOOGLE_MAPS_API_KEY": key})

    asset_lines = [f"GOOGLE_MAPS_API_KEY={key}"]
    if web_key:
        asset_lines.append(f"GOOGLE_MAPS_WEB_API_KEY={web_key}")

    asset_dir = root / "assets" / "env"
    asset_dir.mkdir(parents=True, exist_ok=True)
    (asset_dir / "app.env").write_text("\n".join(asset_lines) + "\n")
    (asset_dir / ".gitkeep").touch()

    print(
        f"Synced Maps key (len={len(key)})"
        + (f" + web key (len={len(web_key)})" if web_key else " (no WEB key)")
        + f" → {secrets.name} + android/local.properties + assets/env/app.env"
    )
    if not web_key:
        print(
            "NOTE: Without GOOGLE_MAPS_WEB_API_KEY, Places HTTP uses the SDK key. "
            "App-restricted keys return REQUEST_DENIED for autocomplete/geocode."
        )


if __name__ == "__main__":
    main()
