# Afropeep Screenshot Configuration

# A list of devices you want to take the screenshots from
devices([
  "iPhone 16 Pro",
  "iPhone 16 Pro Max", 
  "iPad Pro 13-inch (M4)"
])

# Languages for screenshots
languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme("Runner")

# The workspace file path
workspace("ios/Runner.xcworkspace")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# Clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Set the status bar to 9:41 AM, and show full battery and reception
override_status_bar(true)

# Arguments to pass to the app on launch
launch_arguments(["-ui_testing"])

# Stop after first failure
stop_after_first_error(false)

# For more information about all available options run
# fastlane action snapshot
